apiVersion: apps/v1
kind: Deployment
metadata:
  name: apple-deployment
  labels:
    app: apple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apple
  template:
    metadata:
      labels:
        app: apple
    spec:
      containers:
      - name: apple
        image: maheshsoft/apple-app:v1   # replace with your DockerHub username
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - port: 80          # service port inside cluster
      targetPort: 80    # container port
      nodePort: 31008   # external fixed port on worker/master node
  type: NodePort
