apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: attendance-app
  template:
    metadata:
      labels:
        app: attendance-app
    spec:
      containers:
      - name: attendance-app
        image: maheshsoft/attendenceapp1:1.0.0   # Replace with your Docker Hub image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-app-service
spec:
  selector:
    app: attendance-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082   # fixed external port (optional)
  type: NodePort
