name: deploy suresh constraction
on:
  workflow_dispatch:   # manual trigger
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted   # your local laptop runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy StudentApp to Kubernetes
        run: |
          kubectl apply -f app301/app1/k8s-new/deployment.yaml
          kubectl rollout status deployment/student-app
      - name: Validate my deployemnts 
        run: |
          kubectl get deployment student-app
