name: Deploy Apple App

on:
  push:
    branches:
      - main   # trigger only when pushing to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted   # use your self-hosted runner (since it has kubectl & docker)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/apple-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/apple-app:latest

      

      - name: Deploy to Kubernetes
        run: kubectl apply -f app301/appleapp/k8s/apple.yaml
